// Build script for the Design System Documentation Figma plugin.
//
// Figma only loads the two files named in manifest.json (`main` and `ui`), so
// the UI has to be a single self-contained HTML file — no external <script src>.
// esbuild bundles both sides; the UI bundle and CSS get inlined into ui.html here.
//
//   node build.mjs           one-shot build
//   node build.mjs --watch   rebuild on change

import * as esbuild from 'esbuild'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const watch = process.argv.includes('--watch')

const p = (...s) => resolve(root, ...s)

/** Bundle the sandbox half — runs in Figma's JS sandbox, no DOM. */
const sandboxOptions = {
  entryPoints: [p('src/main/code.ts')],
  outfile: p('dist/code.js'),
  bundle: true,
  format: 'iife',
  target: 'es2017',
  logLevel: 'silent',
}

/** Bundle the UI half — runs in the plugin iframe. Written to memory, then inlined. */
const uiOptions = {
  entryPoints: [p('src/ui/index.tsx')],
  bundle: true,
  format: 'iife',
  target: 'es2017',
  write: false,
  logLevel: 'silent',
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.css': 'text' },
}

async function buildUi() {
  const result = await esbuild.build(uiOptions)
  const js = result.outputFiles[0].text
  const css = await readFile(p('src/ui/styles.css'), 'utf8')
  const html = `<!-- Generated by build.mjs — do not edit. Source: src/ui/ -->
<div id="root"></div>
<style>
${css}</style>
<script>
${js}</script>
`
  await mkdir(p('dist'), { recursive: true })
  await writeFile(p('dist/ui.html'), html, 'utf8')
  return js.length + css.length
}

function report(label, err) {
  if (!err) return true
  const msgs = err.errors?.length ? err.errors : [{ text: err.message }]
  console.error(`\n  ✗ ${label} failed`)
  for (const m of msgs) {
    const loc = m.location ? ` ${m.location.file}:${m.location.line}:${m.location.column}` : ''
    console.error(`    ${m.text}${loc}`)
  }
  return false
}

async function buildOnce() {
  const started = Date.now()
  let ok = true
  let uiBytes = 0
  let sandboxBytes = 0

  try {
    await esbuild.build(sandboxOptions)
    sandboxBytes = (await readFile(p('dist/code.js'))).length
  } catch (err) {
    ok = report('sandbox (src/main)', err) && ok
  }

  try {
    uiBytes = await buildUi()
  } catch (err) {
    ok = report('ui (src/ui)', err) && ok
  }

  if (ok) {
    const kb = (n) => `${(n / 1024).toFixed(1)}kb`
    console.log(
      `  ✓ built in ${Date.now() - started}ms — code.js ${kb(sandboxBytes)}, ui.html ${kb(uiBytes)}`
    )
  }
  return ok
}

if (watch) {
  console.log('  watching src/ …')
  await buildOnce()
  const { watch: fsWatch } = await import('node:fs')
  let timer = null
  fsWatch(p('src'), { recursive: true }, () => {
    clearTimeout(timer)
    timer = setTimeout(buildOnce, 80)
  })
} else {
  const ok = await buildOnce()
  if (!ok) process.exit(1)
}
